clear
clc
rho = 1.293; % kg/m^3 %average densisty of air
Cd1 = .04; % drag coeffient above 15 meters height from ground
Cd2 = 0.3; % drag coeffient below 15 meters height from ground
A1 = 0.3; % m^2 % Area of Peregrine Falcon Bird with wings closed
A2 = 2; % m^2 % Area of Peregrine Falcon Bird with wings fully opened
m = 1; % Kg %mass of Peregrine Falcon Bird
g = 9.81; % m/s^2 

%run the simulink model via 'sim' command
sim("simulink_falcon.slx")

%Extract the data generated by simulink
drag_froce_data = ans.drag_force.data;
drag_froce_time = ans.drag_force.time;
drag_force =[drag_froce_time drag_froce_data];

h_data = ans.height.data;
h_time = ans.height.time;
h =[h_time h_data];

%Plot
% Create figure
figure1 = figure('Name','Peregrine Falcon Bird Plot');

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');
% Create plot
plot(drag_force(:,1),drag_force(:,2));
% Create ylabel
ylabel({'Drag Force (N)'});
% Create xlabel
xlabel({'Time (s)'});
% Create title
title({'Drag Force vs Time'});
box(subplot1,'on');
hold(subplot1,'off');

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');
% Create plot
plot(h(:,1),h(:,2));
% Create ylabel
ylabel({'Height (m)'});
% Create xlabel
xlabel({'Time (s)'});
% Create title
title({'Height  vs  Time'});
box(subplot2,'on');
hold(subplot2,'off');